# Generated by Django 4.2.7 on 2025-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_image',
        ),
        migrations.AlterField(
            model_name='user',
            name='program',
            field=models.CharField(choices=[('FINA', 'FINA'), ('QFIN', 'QFIN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='sid',
            field=models.CharField(max_length=8, unique=True, verbose_name='Student ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.CharField(choices=[('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4')], max_length=15),
        ),
    ]
